/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ichat;

import com.ichat.utils.DateUtils;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jivesoftware.smack.Chat;
import org.jivesoftware.smack.ChatManager;
import org.jivesoftware.smack.MessageListener;
import org.jivesoftware.smack.XMPPConnection;
import org.jivesoftware.smack.XMPPException;
import org.jivesoftware.smack.packet.Message;

/**
 *
 * @author zhangjie
 */
public class ChatPanel extends javax.swing.JPanel {

    public void setChatPanel(XMPPConnection conn, String frindsXmppAddress){
        this.conn = conn;
        this.frindsXmppAddress = frindsXmppAddress;
        CreateChatM();
        dateUtils = new DateUtils();
        chatName.setText(frindsXmppAddress);
    }
    /**
     * Creates new form ChatPanel
     */
    public ChatPanel() {
        initComponents();
    }
    private void CreateChatM(){
        if(conn != null){
            chatManager = conn.getChatManager();
            chat = chatManager.createChat(frindsXmppAddress, 
                    new MessageListener(){
                @Override
                public void processMessage(Chat chat, Message msg) {
                    if(msg != null){
                        ChatMessage.append(dateUtils.getHM()+"  "+frindsXmppAddress+": "+msg.getBody()+"\n");
                    }
                }
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chatName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChatMessage = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChatContent = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        SendChatBtn = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ichat/images/login_icon.png"))); // NOI18N

        chatName.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chatName)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        ChatMessage.setEditable(false);
        ChatMessage.setColumns(20);
        ChatMessage.setRows(5);
        jScrollPane1.setViewportView(ChatMessage);

        jScrollPane2.setViewportView(ChatContent);

        jButton1.setText("关闭");

        SendChatBtn.setText("发送");
        SendChatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendChatBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22)
                .addComponent(SendChatBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(SendChatBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SendChatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendChatBtnMouseClicked
        String Content = ChatContent.getText();
        try {
            chat.sendMessage(Content);
             ChatMessage.append(dateUtils.getHM()+"  自己: "+Content+"\n");
             ChatContent.setText("");
        } catch (XMPPException ex) {
            Logger.getLogger(ChatPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SendChatBtnMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ChatContent;
    private javax.swing.JTextArea ChatMessage;
    private javax.swing.JButton SendChatBtn;
    private javax.swing.JLabel chatName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
 private XMPPConnection conn;
 private String frindsXmppAddress;
 private ChatManager chatManager;
 private Chat chat;
 private DateUtils dateUtils; 
}
